version: '3.3'
services:
    zfile:
        container_name: zfile
        restart: always
        ports:
            - '${app_port}:8080'
        volumes:
            - '/${TRIM_APPDEST_VOL}/@appshare/${TRIM_APPNAME}/db:/root/zfile-pro/db'
            - '/${TRIM_APPDEST_VOL}/@appshare/${TRIM_APPNAME}/logs:/root/zfile-pro/logs'
            - '/${TRIM_APPDEST_VOL}/@appshare/${TRIM_APPNAME}/file:/root/zfile-pro/file'
        image: zhaojun1998/zfile-pro:latest
